language: julia
os:
    - linux
    - osx
julia:
    - 0.3
    - 0.4
    - nightly
notifications:
    email: false
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("HDF5")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(Coveralls.process_folder())'; fi
